#TurtleGraphics.py
#Name: Anicet A
#Date:
#Assignment: Lab 4

import turtle #needed generally but not in CodeHS
hideturtle() #hides the default turtle in CodeHS

def drawSquare(myTurtle, size):
    for i in range(4):
        myTurtle.forward(size)
        myTurtle.right(90)

def drawPolygon(cat, sides):
    for s in range(sides):
        cat.forward(60)
        cat.right(360/sides)
        
        
def fillCorner(dog, corner):
    drawSquare(dog, 120)
    
    if corner == 1:
        dog.begin_fill()
        drawSquare(dog, 60)
        dog.end_fill()
    elif corner == 2:
        dog.forward(60)
        dog.begin_fill()
        drawSquare(dog, 60)
        dog.end_fill()
    elif corner == 3:
        dog.left(270)
        dog.forward(60)
        dog.left(90)
        dog.begin_fill()
        drawSquare(dog, 60)
        dog.end_fill()
    elif corner == 4:
        dog.forward(120)
        dog.left(270)
        dog.forward(120)
        dog.right(90)
        dog.begin_fill()
        drawSquare(dog, 60)
        dog.end_fill()

def squaresInSquares(pet, num):
    drawSquare(pet, 120)
    
    if num == 1:
        pet.pendown()
        pet.goto(-5, -5)
        pet.forward(10)
        drawSquare(pet, 110)
    elif num == 2:
        pet.pendown()
        pet.goto(-5, -5)
        pet.forward(10)
        drawSquare(pet,110)
        pet.pendown()
        pet.goto(-10, -10)
        pet.forward(20)
        drawSquare(pet,100)
    elif num == 3: 
        pet.pendown()
        pet.goto(-5, -5)
        pet.forward(10)
        drawSquare(pet,110)
        pet.pendown()
        pet.goto(-10, -10)
        pet.forward(20)
        drawSquare(pet,100)
        pet.pendown()
        pet.goto(-15, -15)
        pet.forward(30)
        drawSquare(pet,90)
    elif num == 4:
        pet.pendown()
        pet.goto(-5, -5)
        pet.forward(10)
        drawSquare(pet,110)
        pet.pendown()
        pet.goto(-10, -10)
        pet.forward(20)
        drawSquare(pet,100)
        pet.pendown()
        pet.goto(-15, -15)
        pet.forward(30)
        drawSquare(pet,90)
        pet.pendown()
        pet.goto(-20, -20)
        pet.forward(40)
        drawSquare(pet,80)
    elif num == 5:
        pet.pendown()
        pet.goto(-5, -5)
        pet.forward(10)
        drawSquare(pet,110)
        pet.pendown()
        pet.goto(-10, -10)
        pet.forward(20)
        drawSquare(pet,100)
        pet.pendown()
        pet.goto(-15, -15)
        pet.forward(30)
        drawSquare(pet,90)
        pet.pendown()
        pet.goto(-20, -20)
        pet.forward(40)
        drawSquare(pet,80)
        pet.pendown()
        pet.goto(-25, -25)
        pet.forward(50)
        drawSquare(pet,70)
    elif num == 6:
        pet.pendown()
        pet.goto(-5, -5)
        pet.forward(10)
        drawSquare(pet,110)
        pet.pendown()
        pet.goto(-10, -10)
        pet.forward(20)
        drawSquare(pet,100)
        pet.pendown()
        pet.goto(-15, -15)
        pet.forward(30)
        drawSquare(pet,90)
        pet.pendown()
        pet.goto(-20, -20)
        pet.forward(40)
        drawSquare(pet,80)
        pet.pendown()
        pet.goto(-25, -25)
        pet.forward(50)
        drawSquare(pet,70)
        pet.pendown()
        pet.goto(-30, -30)
        pet.forward(60)
        drawSquare(pet,60)
    elif num == 7:
        pet.pendown()
        pet.goto(-5, -5)
        pet.forward(10)
        drawSquare(pet,110)
        pet.pendown()
        pet.goto(-10, -10)
        pet.forward(20)
        drawSquare(pet,100)
        pet.pendown()
        pet.goto(-15, -15)
        pet.forward(30)
        drawSquare(pet,90)
        pet.pendown()
        pet.goto(-20, -20)
        pet.forward(40)
        drawSquare(pet,80)
        pet.pendown()
        pet.goto(-25, -25)
        pet.forward(50)
        drawSquare(pet,70)
        pet.pendown()
        pet.goto(-30, -30)
        pet.forward(60)
        drawSquare(pet,60)
        pet.pendown()
        pet.goto(-35, -35)
        pet.forward(70)
        drawSquare(pet,50)
    elif num == 8:
        pet.pendown()
        pet.goto(-5, -5)
        pet.forward(10)
        drawSquare(pet,110)
        pet.pendown()
        pet.goto(-10, -10)
        pet.forward(20)
        drawSquare(pet,100)
        pet.pendown()
        pet.goto(-15, -15)
        pet.forward(30)
        drawSquare(pet,90)
        pet.pendown()
        pet.goto(-20, -20)
        pet.forward(40)
        drawSquare(pet,80)
        pet.pendown()
        pet.goto(-25, -25)
        pet.forward(50)
        drawSquare(pet,70)
        pet.pendown()
        pet.goto(-30, -30)
        pet.forward(60)
        drawSquare(pet,60)
        pet.pendown()
        pet.goto(-35, -35)
        pet.forward(70)
        drawSquare(pet,50)
        pet.pendown()
        pet.goto(-40, -40)
        pet.forward(80)
        drawSquare(pet,40)
    elif num == 9:
        pet.pendown()
        pet.goto(-5, -5)
        pet.forward(10)
        drawSquare(pet,110)
        pet.pendown()
        pet.goto(-10, -10)
        pet.forward(20)
        drawSquare(pet,100)
        pet.pendown()
        pet.goto(-15, -15)
        pet.forward(30)
        drawSquare(pet,90)
        pet.pendown()
        pet.goto(-20, -20)
        pet.forward(40)
        drawSquare(pet,80)
        pet.pendown()
        pet.goto(-25, -25)
        pet.forward(50)
        drawSquare(pet,70)
        pet.pendown()
        pet.goto(-30, -30)
        pet.forward(60)
        drawSquare(pet,60)
        pet.pendown()
        pet.goto(-35, -35)
        pet.forward(70)
        drawSquare(pet,50)
        pet.pendown()
        pet.goto(-40, -40)
        pet.forward(80)
        drawSquare(pet,40)
        pet.pendown()
        pet.goto(-45, -45)
        pet.forward(90)
        drawSquare(pet,30)
    elif num == 10:
        pet.pendown()
        pet.goto(-5, -5)
        pet.forward(10)
        drawSquare(pet,110)
        pet.pendown()
        pet.goto(-10, -10)
        pet.forward(20)
        drawSquare(pet,100)
        pet.pendown()
        pet.goto(-15, -15)
        pet.forward(30)
        drawSquare(pet,90)
        pet.pendown()
        pet.goto(-20, -20)
        pet.forward(40)
        drawSquare(pet,80)
        pet.pendown()
        pet.goto(-25, -25)
        pet.forward(50)
        drawSquare(pet,70)
        pet.pendown()
        pet.goto(-30, -30)
        pet.forward(60)
        drawSquare(pet,60)
        pet.pendown()
        pet.goto(-35, -35)
        pet.forward(70)
        drawSquare(pet,50)
        pet.pendown()
        pet.goto(-40, -40)
        pet.forward(80)
        drawSquare(pet,40)
        pet.pendown()
        pet.goto(-45, -45)
        pet.forward(90)
        drawSquare(pet,30)
        pet.pendown()
        pet.goto(-50, -50)
        pet.forward(100)
        drawSquare(pet,20)
def main():
    myTurtle = turtle.Turtle()
    # drawPolygon(myTurtle, 5) #draws a pentagon
    # drawPolygon(myTurtle, 8) #draws an octogon

    # fillCorner(myTurtle, 2) #draws a square with top right corner filled in.
    # fillCorner(myTurtle, 3) #draws a square bottom left corner filled in.

    # squaresInSquares(myTurtle, 5) #draws 5 concentric squares
    # squaresInSquares(myTurtle, 3) #draws 3 concentric squares


main()
